In [1]:
import pandas as pd
import numpy as np
from datetime import date
import smtplib
from email.mime.text import MIMEText
import os
from dotenv import load_dotenv
from email.mime.multipart import MIMEMultipart

In [3]:
#t = date.today()
#print(t)

t = date(2024, 6, 1)
print(t)

2024-06-01

In [4]:

url = 'https://docs.google.com/spreadsheets/d/140jENzG4GACjso1W9v4Lpl6onnRXZXQ6/export?format=xlsx'

df = pd.read_excel(url)
df

,Username,YOUR FULL NAME,SINGING PART,PHONE NUMBER,BIRTHDAY (Day/Month),BIRTHDATE(REGULARIZED),GENDER,STATE OF ORIGIN,WHY DID YOU JOIN THE CHOIR?,START DATE WITH CHOIR
0,ademufrancis1991@gmail.com,Ademu Francis,Bass,7031992045,2026-02-07 00:00:00,2026-02-07,Male,Edo,To serve God through singing,2015-08-01 00:00:00
1,ademufidelis1994@gmail.com,Ademu Fidelis Oshomah,Bass,8107467794,2026-04-01 00:00:00,2026-04-01,Male,Edo State,I joined because I love music,2019-10-16 00:00:00
2,okekeangel321@gmail.com,Chiemerie Angel okeke,Soprano,9025860975,29th Of April,2026-04-29,Female,Anambra state,"\n""I joined the choir because I'm passionate a...",2022-09-20 00:00:00
3,sucrefashionavenue@gmail.com,Eke Nancy Ngozi,Soprano,7030898210,4th of May,2026-05-04,Female,Abia state,The love for singing,2024-08-30 00:00:00
4,preciousonuoha4@gmail.com,Onuoha Precious Cecilia,Alto,8094329087,May 1st,2026-05-01,Female,Abia state,That's because of their unique performance dur...,2017-06-18 00:00:00
5,irohlucia@gmail.com,Iroh Lucia Onyinye,Alto,8100518110,13th may,2026-05-13,Female,Imo state,Cos I love singing,2020-02-19 00:00:00
6,excaliburpablo@gmail.com,Ogoke Francis Uchechukwu,Bass,9117320945,March 5th,2026-03-05,Male,Imo,To sing for God.,2017-03-16 00:00:00
7,etonihuchisom@gmail.com,Etonihu Munachiso Assumpta,Soprano,8124667461,August 28th,2026-08-28,Female,Imo state,I joined the choir because I love singing and ...,2011-07-17 00:00:00
8,tonyemzy1@gmail.com,NWOBODO Anthony Emeka,Tenor,8132969872,2026-07-02 00:00:00,2026-07-02,Male,Enugu,For the love of music,2013-01-10 00:00:00
9,atueyichinwe@gmail.com,ATUEYI PRECIOUS CHINWENDU,Soprano,8144562414,2013-11-01 00:00:00,2026-11-13,Female,IMO STATE,Because I love music,2023-11-19 00:00:00
10,kadoanyachinenye@gmail.com,Okafor Chinenye Rosemary,Alto,8172595218,2026-05-18 00:00:00,2026-05-18,Female,Delta state,Cause i love to sing and to render my service ...,2024-08-30 00:00:00
11,anisiobinzubechi@gmail.com,Anisiobi Nzubechukwu Anthony,Bass,8098989005,2026-04-18 00:00:00,2026-04-18,Male,Anambra,Was drawn to chorale harmony.,2019-01-06 00:00:00
12,chiamakamarian26@gmail.com,Udi Marian,Soprano,8130153797,7th January,2026-01-07,Female,Imo,To use my talents in serving God here on Earth.,2018-03-20 00:00:00
13,mimiokonkwo12@gmail.com,Akanuno nmesoma,Alto,9069032299,24th june,2026-06-24,Female,Anambra state,"Because I love to sing ,singing helps draw me ...",2018-08-30 00:00:00
14,emmy41096@gmail.com,CHUKWU CHIDERA EMMANUEL,Tenor,9027569537,2026-12-01 00:00:00,2026-12-01,Male,ENUGU,TO PRAISE THE LORD,2022-10-22 00:00:00
15,davidemmwnuel@gmail.com,David Emmanuel John,Tenor,2350000000000,2026-06-01 00:00:00,2026-06-01,Male,Ebonyi state,To sing to thy lord,2022-05-22 00:00:00
16,jobaluge@gmail.com,Job Izebhokale Aluge,Bass,8163803625,16th July,2026-07-16,Male,Edo,To learn how to sing well so that I can pray t...,2015-08-05 00:00:00
17,meckurykingsley@gmail.com,Madu Emeka Kingsley,Tenor,8162465247,2026-10-25 00:00:00,2026-10-25,Male,Imo,"To learn, to grow, to meet good musicians.",2024-08-30 00:00:00
18,ozohmichael2006@gmail.com,Ozoh Michael Mmaduabuchi,Tenor,9130296926,"12th, October.",2026-10-12,Male,Anambra,I joined the Choir to in order to improve my ...,2021-08-25 00:00:00
19,agbochinecherem9@gmail.com,Agbo Chinecherem Emmanuella,Soprano,7076950229,13th of June,2026-06-13,Female,Enugu State,I love Music and also wants to bring out my be...,2023-03-26 00:00:00
20,brunobrowncg@gmail.com,BRUNO GUBOR,Tenor,8061638454,20th February,2026-02-20,Male,IMO,I love good music,2023-05-01 00:00:00
21,chikakogolo@gmail.com,Maryann Okafor,Alto,9026757876,10th of May,2026-05-10,Female,Delta,I love singing,2018-10-01 00:00:00
22,stephaneapedo2@gmail.com,APEDO KOKOU STEPHANE,Tenor,07012591694 - 09150776298,2026-10-02 00:00:00,2026-10-02,Male,ECOWAS,I love singing to the Lord,2014-02-14 00:00:00
23,ogebaby652@gmail.com,Kingsley ogechi,Soprano,7061058341,2026-08-21 00:00:00,2026-08-21,Female,Enugu State,I love singing,2021-09-19 00:00:00
24,onuoha.anasthesia@gmail.com,Onuoha chidinma Favour,Soprano,8161827910,1999-06-18 00:00:00,2026-06-18,Female,Abia state,Passion and gift,0020-06-18
25,lexzymuomah27@gmail.com,Perpetual Chinenye Ademu,Soprano,9064027221,2026-04-27 00:00:00,2026-04-27,Female,Anambra State,To serve God with my Beautiful Talent(Singing)...,2013-11-10 00:00:00
26,adaeze.joy.779@gmail.com,Chioma Joy Okeke,Alto,8108672207,2003-06-15 00:00:00,2026-06-15,Female,Anambra State,I no even know. I just see myself for choir.,2012-06-15 00:00:00
27,redivy26102006@gmail.com,Igwe Esther,Alto,9165223309,2026-10-26 00:00:00,2026-10-26,Female,Abia State,I joined the choir because singing is my way o...,2021-09-22 00:00:00
28,florencelucy6@gmail.com,Ibeh Florence Ginika,Soprano,8064809835,2026-11-11 00:00:00,2026-11-11,Female,Imo,To make good use of what God has given me,2016-01-02 00:00:00
29,rebeccae152@gmail.com,Rebecca Emmanuel,Soprano,9121532757,11th of October,2026-10-11,Female,Akwa ibom,"Because, I love singing",2019-08-11 00:00:00
30,ukpongemma2@gmail.com,"Ukpong, ( Emmanuel )Â²",Bass,7062310605,2026-05-01 00:00:00,2026-05-01,Male,Akwa-Ibom state,"To Sing Praises only to God-Almigty, my Creator.",2021-05-05 00:00:00
31,destinymbah112@gmail.com,MBAH GLORY,Alto,9028561003,11th November,2026-11-11,Female,CROSS RIVER STATE,To Sing Praises to the Lord & Cause Singing ha...,2015-08-11 00:00:00
32,abbypate05@gmail.com,Omotayo patience,Alto,9069996524,2005-05-01 00:00:00,2005-05-01,Female,Ondo state,Music is life,2024-09-20 00:00:00
33,juliejuliu@gmail.com,Juliana Julius,Alto,8164657524,2011-10-01 00:00:00,2011-10-01,Female,Edo state,To praise God,2018-05-20 00:00:00
34,favourcecilia641@gmail.com,Anosike Favour Cecilia Onyinyechi,Soprano,8146741887,2026-11-10 00:00:00,2026-11-10,Female,Imo State,"I love music, I want to improve in singing a...",2022-06-15 00:00:00
35,ogebaby652@gmail.com,Kingsley oge,Soprano,7061058341,2026-08-21 00:00:00,2026-08-21,Female,Ebonyi,I love singing,2019-10-23 00:00:00
36,obinna.b.ukwueze@gmail.com,Obinna Benedict Ukwueze,Bass,7063690997,2nd July,2026-07-02,Male,Enugu state,Because of my love for music,2013-03-13 00:00:00
37,irohlucia@gmail.com,Onyinyechi Lucy,Alto,8100518110,2026-05-13 00:00:00,2026-05-13,Female,Imo,Because I love singing,2020-01-08 00:00:00
38,adaeze.joy.779@gmail.com,Chioma Joy Okeke,Alto,8108672207,2026-06-15 00:00:00,2026-06-15,Female,Anambra state,Them force me join,2010-12-01 00:00:00
39,ordinakahchristianah26@gmail.com,Nwaiwu Christianah Ordinakah,Alto,9161073390,March,NaT,Female,Imo,Passion for music,2016-03-23 00:00:00
40,emmy41096@gmail.com,CHUKWU CHIDERA EMMANUEL,Tenor,9027568537,2026-12-01 00:00:00,2026-12-01,Male,ENUGU,TO PRAISE THE LORD,2022-10-23 00:00:00
41,adaobijoy333@gmail.com,Onwuasoeze joy,Alto,7016584549,15th June,2026-06-15,Female,Anambra state,...,2019-09-01 00:00:00
42,froshv55@gmail.com,Nwenyi Victory ngozi,Soprano,8025790912,2030-01-01 00:00:00,2026-01-20,Female,Anambra,Love singing,2023-08-10 00:00:00
43,igweifunanya123@gmail.com,Igwe Ifunanya Vivian,Alto,7086304948,4th October,2026-10-04,Female,Abia,Give my service to God and to connect with others,2025-01-05 00:00:00
44,chukwuchioma473@gmail.com,MRS EZE CHIOMA,Soprano,9021810896,23 of April,2026-04-23,Female,Enugu,To b more closer to God and sing for christ,2022-01-01 00:00:00
45,fabianeze85@gmail.com,MR EZE FABIAN,Bass,8066591805,3rd July,2026-07-03,Male,Enugu,To sing praises unto the lord,2021-02-10 00:00:00
46,danielobi567nna@gmail.com,Gilbert munachimso Elvis,Bass,7012651467,2008-03-20 00:00:00,2026-03-20,Male,Imo state,I love singing,2024-09-07 00:00:00
47,NaN,Kyle,NaN,NaN,NaN,2026-04-06,NaN,NaN,NaN,NaN

In [5]:
birthdates = df[['BIRTHDATE(REGULARIZED)', 'YOUR FULL NAME ']]
birthdates

   BIRTHDATE(REGULARIZED)                     YOUR FULL NAME
0              2026-02-07                      Ademu Francis
1              2026-04-01              Ademu Fidelis Oshomah
2              2026-04-29               Chiemerie Angel okeke
3              2026-05-04                    Eke Nancy Ngozi
4              2026-05-01            Onuoha Precious Cecilia
5              2026-05-13                  Iroh Lucia Onyinye
6              2026-03-05            Ogoke Francis Uchechukwu
7              2026-08-28          Etonihu Munachiso Assumpta
8              2026-07-02               NWOBODO Anthony Emeka
9              2026-11-13          ATUEYI PRECIOUS CHINWENDU
10             2026-05-18           Okafor Chinenye Rosemary
11             2026-04-18       Anisiobi Nzubechukwu Anthony
12             2026-01-07                          Udi Marian
13             2026-06-24                    Akanuno nmesoma
14             2026-12-01             CHUKWU CHIDERA EMMANUEL
15             2026-06-01                 David Emmanuel John
16             2026-07-16               Job Izebhokale Aluge
17             2026-10-25                 Madu Emeka Kingsley
18             2026-10-12            Ozoh Michael Mmaduabuchi
19             2026-06-13        Agbo Chinecherem Emmanuella
20             2026-02-20                        BRUNO GUBOR
21             2026-05-10                     Maryann Okafor
22             2026-10-02               APEDO KOKOU STEPHANE
23             2026-08-21                     Kingsley ogechi
24             2026-06-18             Onuoha chidinma Favour
25             2026-04-27           Perpetual Chinenye Ademu
26             2026-06-15                   Chioma Joy Okeke
27             2026-10-26                         Igwe Esther
28             2026-11-11                Ibeh Florence Ginika
29             2026-10-11                    Rebecca Emmanuel
30             2026-05-01              Ukpong, ( Emmanuel )Â²
31             2026-11-11                          MBAH GLORY
32             2005-05-01                    Omotayo patience
33             2011-10-01                      Juliana Julius
34             2026-11-10  Anosike Favour Cecilia Onyinyechi
35             2026-08-21                        Kingsley oge
36             2026-07-02            Obinna Benedict Ukwueze
37             2026-05-13                     Onyinyechi Lucy
38             2026-06-15                    Chioma Joy Okeke
39                    NaT        Nwaiwu Christianah Ordinakah
40             2026-12-01            CHUKWU CHIDERA EMMANUEL
41             2026-06-15                     Onwuasoeze joy
42             2026-01-20               Nwenyi Victory ngozi
43             2026-10-04               Igwe Ifunanya Vivian
44             2026-04-23                      MRS EZE CHIOMA
45             2026-07-03                       MR EZE FABIAN
46             2026-03-20           Gilbert munachimso Elvis
47             2026-04-06                                Kyle

In [6]:
load_dotenv()
EMAIL_ADDRESS = os.getenv('Email_Address')
EMAIL_PASSWORD = os.getenv('Email_Password')
SMTP_SERVER = 'smtp.gmail.com'
PORT = 587

def send_birthday_email(recipient_email, subject, body):
    msg = MIMEMultipart()
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = recipient_email
    msg['Subject'] = subject
    
    msg.attach(MIMEText(body, 'plain'))
    
    try:
        with smtplib.SMTP(SMTP_SERVER, PORT) as server:
            server.starttls()
            server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            server.sendmail(EMAIL_ADDRESS, recipient_email, msg.as_string())
        print(f'Email sent sucessfully')
    except Exception as e:
        print(f'Failed to send email: {e}')

In [7]:
recipient = 'anisiobinzubechi@gmail.com'
subject = 'Birthday Reminder!'

In [8]:
for index, row in df.iterrows():
    birthdate = row['BIRTHDATE(REGULARIZED)']
    name = row['YOUR FULL NAME ']
    
    if birthdate.month == t.month and birthdate.day == t.day:
        print(f"Today is {name}'s birthday!")
        body = f"Today is {name}'s birthday!"
        
        send_birthday_email (recipient, subject, body)

Today is David Emmanuel John's birthday!
Failed to send email: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond